version: "3.1"

services:
    db:
        container_name: corelab_database
        image: postgres:14.2-alpine
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=default
            - POSTGRES_NAME=corelab
        volumes:
            - ./data:/data/postgres
        ports:
            - "3333:5432"

    # app:
    #     container_name: api
    #     build: .
    #     depends_on:
    #         - db
    #     restart: always
    #     ports:
    #         - "3001:3000"
    #     volumes:
    #         - .:/usr/app
    #     command: sh -c "npm run test && npm run typeorm migration:run -- -d src/data-source && npm run dev"
