version: "3.1"

services:
    db:
        container_name: corelab_database
        image: postgres:14.2-alpine
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=default
            - POSTGRES_NAME=corelab
        volumes:
            - ./data:/data/postgres
        ports:
            - "3333:5432"

    db_teste:
        container_name: corelab_database_testes
        image: postgres:14.2-alpine
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=teste
            - POSTGRES_NAME=corelab
        volumes:
            - ./data:/data/postgres
        ports:
            - "8080:5432"
        # app:
        #   container_name: api
        #   build: .
        #   restart: always
        #   ports:
        #     - "3001:3001"
        #   volumes:
        #     - .:/usr/app
        #   command: npm run dev
